### ISSUE TITLE
integration mapping in API Gateway

### ISSUE THREAD

**Issue by danhanley** [nateyolles/slack-pokerbot#1]
I'm getting the follow response in Slack from the Lambda function:

PokerBot BOT [5:15 PM] Only visible to you
{"message": "Could not parse request body into json: Unrecognized token \'token\': was expecting \'null\', \'true\', \'false\' or NaN\n at [Source: [B@238685e5; line: 1, column: 7]"}

My guess is tat I have not configured the Integration Maping in the API Gateway correctly (in fact, I've left it on it's defaults).

Should I be putting a mapping template in here?

Cheers

Dan

**Comment by danhanley** [comment]
As suspected I needed an integration mapping of:

{
"body" : $input.json('$')
}

for application/x-www-form-urlencoded data.

**Comment by nateyolles** [comment]
Thank you for posting your findings.
